default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sistemaReceitas
  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  database: sistemaReceitas
  username: postgres
  password: 123456
  host: localhost
  port: 5432

production:
  <<: *default
  database: sistemaReceitas
  username: postgres
  password: 123456
  host: localhost
  port: 5432